undertow/src/main/java/org/wildfly/elytron/web/undertow/server/SecurityContextImpl.java
undertow/src/test/java/org/wildfly/elytron/web/undertow/server/DefaultServer.java

deprecated setResponseCode is alias for setStatusCode
deprecated ENABLE_CONNECTOR_STATISTICS is alias for ENABLE_STATISTICS

[#21] Get rid of deprecated Undertow API

---

undertow/src/main/java/org/wildfly/elytron/web/undertow/server/ElytronHttpExchange.java
undertow/src/main/java/org/wildfly/elytron/web/undertow/server/ScopeSessionListener.java

* Requires https://github.com/wildfly-security/wildfly-elytron/pull/470

[ELY-624] - Changes to HttpScope API

---

undertow/src/test/java/org/wildfly/elytron/web/undertow/server/ClientCertAuthenticationTest.java

It makes trouble on ibm java. Use getDefaultAlgorithm().

[22] Replace hardcoded algorithm "SunX509"

---

.travis-settings.xml
.travis.yml

To resolve delayed synchronization of Elytron bits to Maven Central.

Added custom settings.xml to referrence JBoss Maven repository

---

undertow/src/test/java/org/wildfly/elytron/web/undertow/server/FormAuthenticationWithClusteredSSOTest.java

Requires https://github.com/wildfly-security/wildfly-elytron/pull/633

Use non-deprecated SingleSignOnSessionFactory constructor.

---

undertow/src/test/java/org/wildfly/elytron/web/undertow/server/ClientCertAuthenticationTest.java

Tests update related to https://github.com/wildfly-security/wildfly-elytron/pull/646

[ELY-905] CLIENT_CERT mechanism name by HttpServletRequest

---

pom.xml
undertow/src/main/java/org/wildfly/elytron/web/undertow/server/ElytronHttpExchange.java

Depends on https://github.com/wildfly-security/wildfly-elytron/pull/651.

[ELY-911] - Add method to obtain the request relative path

---

undertow/src/main/java/org/wildfly/elytron/web/undertow/server/SecurityContextImpl.java

Depends on https://github.com/wildfly-security/wildfly-elytron/pull/652

[ELY-904] - Logout notification support for HTTP-based authentication mechanisms

---

undertow/src/main/java/org/wildfly/elytron/web/undertow/server/ElytronHttpExchange.java

Elytron Web: https://issues.jboss.org/browse/ELY-981

[ELY-981] Coverity static analysis: Performace optimalization in map iterating

---

undertow/src/main/java/org/wildfly/elytron/web/undertow/server/ElytronRunAsHandler.java
undertow/src/main/java/org/wildfly/elytron/web/undertow/server/SecurityContextImpl.java

Requires Elytron Beta29 to compile

Change to using FlexibleIdentityAssociation

---

undertow/src/main/java/org/wildfly/elytron/web/undertow/server/ElytronHttpExchange.java

This is the Elytron Web side of https://github.com/wildfly-security/wildfly-elytron/pull/722

[ELY-621] Add support for obtaining the peer certificates including renegotiating the SSL session if possible.

---

pom.xml
undertow/pom.xml
undertow/src/test/java/org/wildfly/elytron/web/undertow/server/BearerTokenAuthenticationTest.java

Depends on https://github.com/wildfly-security/wildfly-elytron/pull/739

[ELY-1025] - Tests for  Bearer Token HTTP Authentication Mechanism

---

undertow/src/test/java/org/wildfly/elytron/web/undertow/server/ClientCertAuthenticationTest.java
undertow/src/test/java/org/wildfly/elytron/web/undertow/server/FormAuthenticationTest.java

Changes based on Elytron ```1.1.0.Beta52-SNAPSHOT```.

Fixing errors due to change in Elytron API

---

undertow/src/main/java/org/wildfly/elytron/web/undertow/server/ElytronAccount.java
undertow/src/main/java/org/wildfly/elytron/web/undertow/server/ElytronHttpExchange.java

https://issues.jboss.org/browse/ELY-1361
https://issues.jboss.org/browse/JBEAP-10647

[ELY-1361] Removing unnecessary parallel streams

---

undertow/src/main/java/org/wildfly/elytron/web/undertow/server/SecurityContextImpl.java

This is dependent on the following WildFly Elytron PR https://github.com/wildfly-security/wildfly-elytron/pull/1075

Resolves #117 Remove programmatic login code and instead call Elytron APIs

---

undertow/src/main/java/org/wildfly/elytron/web/undertow/server/ElytronContextAssociationHandler.java
undertow/src/main/java/org/wildfly/elytron/web/undertow/server/SecurityContextImpl.java
undertow/src/test/java/org/wildfly/elytron/web/undertow/server/AbstractHttpServerMechanismTest.java
undertow/src/test/java/org/wildfly/elytron/web/undertow/server/BasicAuthenticationTest.java
undertow/src/test/java/org/wildfly/elytron/web/undertow/server/ConstraintDrivenAuthenticationModeTest.java

backport of #133 to 1.0.x branch
JIRA: https://issues.jboss.org/browse/JBEAP-15054
Upstream: https://issues.jboss.org/browse/ELY-1609
Upstream PR: #133

[ELYWEB-8] Adding Undertow Constant-Driven authentication mode

---

undertow-servlet/src/main/java/org/wildfly/elytron/web/undertow/server/servlet/AuthenticationManager.java

JIRA: https://issues.jboss.org/browse/ELYWEB-13

[ELYWEB-13] Enable constrain driven auth mode during deployment

---

undertow-servlet/pom.xml
undertow-servlet/src/main/java/org/wildfly/elytron/web/undertow/server/servlet/AuthenticationManager.java
undertow-servlet/src/main/java/org/wildfly/elytron/web/undertow/server/servlet/CleanUpHandler.java
undertow-servlet/src/main/java/org/wildfly/elytron/web/undertow/server/servlet/CleanUpTask.java
undertow-servlet/src/main/java/org/wildfly/elytron/web/undertow/server/servlet/ElytronServletContextAssociationHandler.java
undertow-servlet/src/main/java/org/wildfly/elytron/web/undertow/server/servlet/RequestResponseAccessor.java
undertow-servlet/src/main/java/org/wildfly/elytron/web/undertow/server/servlet/ServletSecurityContextImpl.java
undertow/src/main/java/org/wildfly/elytron/web/undertow/server/ElytronAccount.java
undertow/src/main/java/org/wildfly/elytron/web/undertow/server/ElytronContextAssociationHandler.java
undertow/src/main/java/org/wildfly/elytron/web/undertow/server/SecurityContextImpl.java

Changes are still being applied to the topic branch but I wanted to get the PR out there.

[ELYWEB-7] JASPI Integration

---

undertow-servlet/pom.xml

https://issues.jboss.org/browse/ELYWEB-29

[ELYWEB-29] Add jboss repository to project

---

undertow/src/main/java/org/wildfly/elytron/web/undertow/server/ElytronHttpExchange.java

https://issues.jboss.org/browse/ELYWEB-51

[ELYWEB-51] Update ElytronHttpExchange to obtain SSLSession from Undertow's SSLSessionInfo.

---

pom.xml

https://issues.jboss.org/browse/ELYWEB-56
https://issues.jboss.org/browse/ELYWEB-57

[ELYWEB-56] / [ELYWEB-57] JBoss Parent and Checkstyle Config Updates.

---

.travis.yml

https://issues.jboss.org/browse/ELYWEB-68

[ELYWEB-68] Upgrade Travis CI to OpenJDK 11

---

undertow-servlet/src/main/java/org/wildfly/elytron/web/undertow/server/servlet/ServletSecurityContextImpl.java

https://issues.jboss.org/browse/ELYWEB-67

[ELYWEB-67] Ensure we use a doPrivileged to obtain the AuthConfigFactory if we have a SecurityManager installed.

---

pom.xml
undertow-servlet/pom.xml

https://issues.jboss.org/browse/ELYWEB-66

[ELYWEB-66] Upgrade WildFly Elytron to 1.10.3.Final + component upgrades

---

pom.xml

https://issues.jboss.org/browse/ELYWEB-73

[ELYWEB-73] Upgrade Undertow to 2.0.27.Final

---

pom.xml
undertow-common-test/pom.xml
undertow-common-test/src/main/java/org/wildfly/elytron/web/undertow/common/AbstractHttpServerMechanismTest.java
undertow-common-test/src/main/java/org/wildfly/elytron/web/undertow/common/ClientCertAuthenticationBase.java
undertow-servlet/pom.xml
undertow-servlet/src/main/java/org/wildfly/elytron/web/undertow/server/servlet/AuthenticationManager.java
undertow-servlet/src/test/java/org/wildfly/elytron/web/undertow/server/servlet/util/UndertowServletServer.java
undertow/pom.xml

https://issues.jboss.org/browse/ELYWEB-78

[ELYWEB-78] Remove deprecated Elytron modules and reference new classes

---

pom.xml

https://issues.redhat.com/browse/ELYWEB-81

[ELYWEB-81] Upgrade nimbus-jose-jwt to 8.2.1.

---

pom.xml

https://issues.redhat.com/browse/ELYWEB-80

[ELYWEB-80] Upgrade Undertow to 2.0.28.Final

---

pom.xml

https://issues.redhat.com/browse/ELYWEB-83

[ELYWEB-83] Upgrade WildFly Elytron to 1.11.0.CR3

---

pom.xml

https://issues.redhat.com/browse/ELYWEB-84

[ELYWEB-84] Upgrade Undertow to 2.0.29.Final

---

pom.xml

https://issues.redhat.com/browse/ELYWEB-89

[ELYWEB-89] Upgrade Infinispan to 9.3.8.Final

---

pom.xml

https://issues.redhat.com/browse/ELYWEB-90

[ELYWEB-90] HTTP Components component upgrades.

---

pom.xml

https://issues.redhat.com/browse/ELYWEB-91

[ELYWEB-91] Upgrade WildFly Elytron to 1.11.1.Final

---

pom.xml

https://issues.redhat.com/browse/ELYWEB-92
https://issues.redhat.com/browse/ELYWEB-93
https://issues.redhat.com/browse/ELYWEB-100
https://issues.redhat.com/browse/ELYWEB-101

Component Upgrades

---

pom.xml

https://issues.redhat.com/browse/ELYWEB-102

[ELYWEB-102] Upgrade WildFly Elytron to 1.11.3.Final

---

undertow-servlet/src/main/java/org/wildfly/elytron/web/undertow/server/servlet/ElytronHttpServletExchange.java

https://issues.redhat.com/browse/ELYWEB-103

[ELYWEB-103] Change Session ID on authentication.

---

pom.xml

https://issues.redhat.com/browse/ELYWEB-115

[ELYWEB-115] Upgrade Undertow to 2.1.4.Final

---

pom.xml
undertow-common-test/pom.xml
undertow-servlet/pom.xml
undertow/pom.xml

https://issues.redhat.com/browse/ELYWEB-120
https://issues.redhat.com/browse/ELYWEB-121
https://issues.redhat.com/browse/ELYWEB-122
https://issues.redhat.com/browse/ELYWEB-123

Latest round of component upgrades

---

.github/workflows/pr-ci.yaml

https://issues.redhat.com/browse/ELYWEB-119

[ELYWEB-119] Add a new GitHub Workflow for CI

---

pom.xml

https://issues.redhat.com/browse/ELYWEB-127

[ELYWEB-127] Upgrade WildFly Elytron to 1.15.0.CR1

---

pom.xml

https://issues.redhat.com/browse/ELYWEB-134 - Undertow 2.2.7.Final
https://issues.redhat.com/browse/ELYWEB-135 - WildFly Elytron 1.15.3.Final

[ELYWEB-134] / [ELYWEB-135] Component Upgrades

---

undertow/src/main/java/org/wildfly/elytron/web/undertow/server/SecurityContextImpl.java

https://issues.redhat.com/browse/ELYWEB-133

[1.6.x] [ELYWEB-113] Ensure the HttpAuthenticator is available to both the authenticate() and the login(username, password) method.

---

undertow/src/main/java/org/wildfly/elytron/web/undertow/server/SecurityContextImpl.java

https://issues.redhat.com/browse/ELYWEB-133

[1.9.x] [ELYWEB-113] Ensure the HttpAuthenticator is available to both the authenticate() and the login(username, password) method.
